apiVersion: v1
kind: Service
metadata:
  name: nginx-5
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: nginx-5
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx-5
  type: LoadBalancer